language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17 and GLUT
  - sudo apt-get install -qq g++-6 freeglut3-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  # Build and test
  - g++ -std=c++17 main.cpp gameboard.cpp block.cpp player.cpp wall.cpp floor.cpp testing.cpp gameboard_tests.cpp block_tests.cpp player_tests.cpp wall_tests.cpp floor_tests.cpp gui.cpp -o infinity -lstdc++fs -lGL -lglut
  - ./infinity test